name: Coverage Report

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        # Todas las órdenes se ejecutan desde DATAFILLER
        working-directory: DATAFILLER

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP & extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: xdebug

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Run PHPUnit (with coverage)
        run: vendor/bin/phpunit

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Publicar el HTML generado por PHPUnit en DATAFILLER/coverage-report
          publish_dir: DATAFILLER/coverage-report
          publish_branch: gh-pages
          user_name: github-actions
          user_email: github-actions@github.com