name: Generate Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**/*.md'
      - 'docs/docfx.json'
      - 'FD*.md'
      - 'DATAFILLER/**/*.php'

jobs:
  build-docs:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup DocFX
      run: |
        Invoke-WebRequest -Uri "https://github.com/dotnet/docfx/releases/download/v2.78.3/docfx-win-x64-v2.78.3.zip" -OutFile "docfx.zip"
        Expand-Archive -Path "docfx.zip" -DestinationPath "docfx"
        
    - name: Build Documentation (HTML)
      run: |
        cd docs
        ..\docfx\docfx.exe docfx.json
        
    - name: Build Documentation (PDF)
      run: |
        cd docs
        ..\docfx\docfx.exe pdf docfx.json
      continue-on-error: true
        
    - name: Create docs folder structure
      run: |
        mkdir deploy
        mkdir deploy\docs
        xcopy docs\_site deploy\docs /E /I
        if exist docs\_pdf xcopy docs\_pdf deploy\docs\pdf /E /I
        xcopy DATAFILLER deploy /E /I
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'datafiller2'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./deploy
        
    - name: Upload artifact with PDF
      uses: actions/upload-artifact@v4
      with:
        name: datafiller-documentation-${{ github.run_number }}
        path: |
          docs/_site
          docs/_pdf
        retention-days: 30