name: Generate Documentation

on:
  push:
    paths:
      - 'docs/**/*.md'
      - 'docs/docfx.json'
  pull_request:
    paths:
      - 'docs/**/*.md'

jobs:
  build-docs:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup DocFX
      run: |
        Invoke-WebRequest -Uri "https://github.com/dotnet/docfx/releases/download/v2.78.3/docfx-win-x64-v2.78.3.zip" -OutFile "docfx.zip"
        Expand-Archive -Path "docfx.zip" -DestinationPath "docfx"
        
    - name: Build Documentation
      run: |
        cd docs
        ../docfx/docfx.exe docfx.json
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_site