name: Generate Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**/*.md'
      - 'docs/docfx.json'
      - 'DATAFILLER/**/*.php'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**/*.md'

jobs:
  build-docs:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup DocFX
      run: |
        Invoke-WebRequest -Uri "https://github.com/dotnet/docfx/releases/download/v2.78.3/docfx-win-x64-v2.78.3.zip" -OutFile "docfx.zip"
        Expand-Archive -Path "docfx.zip" -DestinationPath "docfx"
        
    - name: Build Documentation
      run: |
        cd docs
        ..\docfx\docfx.exe docfx.json
        
    - name: Upload documentation artifact
      uses: actions/upload-artifact@v4
      with:
        name: datafiller-documentation-${{ github.run_number }}
        path: docs/_site
        retention-days: 30