name: Terraform Cost Estimation with Infracost

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  infracost:
    name: Estimate Infrastructure Cost
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Install Infracost CLI
        run: |
          curl -s https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
          echo "$HOME/.infracost/bin" >> $GITHUB_PATH

      - name: Setup Infracost API Key
        run: echo "INFRACOST_API_KEY=${{ secrets.INFRACOST_API_KEY }}" >> $GITHUB_ENV

      - name: Generate cost estimate
        run: |
          infracost breakdown --path . \
            --terraform-plan-flags="-out=tfplan" \
            --format table \
            --out-file infracost-report.md

      - name: Mostrar reporte en resumen
        run: |
          echo "## Estimación de Costos con Infracost" >> $GITHUB_STEP_SUMMARY
          cat infracost-report.md >> $GITHUB_STEP_SUMMARY
