name: SonarCloud Analysis for PHP

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, zip
          tools: composer

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.11.0
        with:
          projectKey: apibankk_proyecto
          organization: apibankk
          token: ${{ secrets.SONAR_TOKEN }}
          # Opcional: si quieres especificar ruta y otros parámetros
          extraProperties: |
            sonar.sources=DATAFILLER
            sonar.php.coverage.reportPaths=coverage.xml
